import type {Metadata} from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata: Metadata = {
  title: 'Momentum BI',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased flex flex-col min-h-screen">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <div className="flex-grow flex flex-col">
            {children}
            </div>
            <footer className="w-full bg-background border-t border-border p-4 text-sm text-muted-foreground shrink-0">
                <div className="container mx-auto flex justify-between items-center">
                    <span>Momentum BI</span>
                    <span>Developed by Harpinder Singh, CEO Office with Care</span>
                </div>
            </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
